services:
  - type: web
    name: mylife-cashflow-api
    runtime: node
    plan: free
    buildCommand: npm install --omit=dev --ignore-scripts
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FLW_SECRET_KEY
        sync: false
      - key: FLW_SECRET_HASH
        sync: false
      - key: FLW_PUBLIC_KEY
        sync: false
      - key: FLW_CLIENT_ID
        sync: false
      - key: FLW_CLIENT_SECRET
        sync: false
